const data = [
  {
    id: "4",
    name: "Pesto Pasta",
    username: "Srivardhan",
    tags: ["italian", "pasta", "vegetarian", "easy"],
    prepareTime: 15,
    cookTime: 10,
    ingredients: [
      { name: "Pasta (your choice)" },
      { name: "Pesto (store-bought or homemade)" },
      { name: "Cherry tomatoes (optional)" },
      { name: "Parmesan cheese" },
      { name: "Pine nuts (optional)" },
      { name: "Fresh basil (optional)" },
      { name: "Olive oil (optional)" },
    ],
    steps: [
      "Cook pasta according to package instructions",
      "Reserve some pasta water before draining",
      "Toss cooked pasta with pesto, adding a little pasta water to create a sauce",
      "Garnish with cherry tomatoes, parmesan cheese, pine nuts, and fresh basil (optional)",
    ],
    servings: 4,
    servingSizes: [{ scale: 1, qty: 1 }],
    ratings: 4.5,
    users: 2345,
    img: "https://i.pinimg.com/originals/b5/3a/bb/b53abb21f73c2c81cab6eb0b3437984b.jpg ",
  },
  {
    id: "24",
    name: "Spaghetti and Meatballs",
    username: "Sn",
    tags: ["italian", "pasta", "meatballs", "dinner"],
    prepareTime: 30,
    cookTime: 40,
    ingredients: [
      { name: "Ground beef" },
      { name: "Breadcrumbs" },
      { name: "Parmesan cheese" },
      { name: "Egg" },
      { name: "Spaghetti" },
      { name: "Tomato sauce" },
      { name: "Onion" },
      { name: "Garlic" },
      { name: "Italian seasoning" },
    ],
    steps: [
      "Combine ground beef, breadcrumbs, parmesan cheese, egg, and seasonings to make meatballs",
      "Brown meatballs in a pan",
      "Simmer meatballs in tomato sauce with chopped onion and garlic",
      "Cook spaghetti according to package instructions",
      "Serve spaghetti with meatballs and sauce, topped with additional parmesan cheese (optional)",
    ],
    servings: 4,
    servingSizes: [{ scale: 1, qty: 1, units: "plate" }],
    ratings: 4.6,
    users: 44,
    img:"https://www.carolynscooking.com/wp-content/uploads/2021/09/Italian-Meatballs-8.jpg"
  },
  {
    id: "25",
    name: "Stir-Fried Vegetables with Tofu ",
    username: "John Doe",
    tags: ["vegetarian", "vegan", "stir-fry", "tofu", "lunch", "dinner"],
    prepareTime: 10,
    cookTime: 15,
    ingredients: [
      { name: "Tofu" },
      { name: "Broccoli florets" },
      { name: "Bell peppers" },
      { name: "Soy sauce" },
      { name: "Rice vinegar" },
      { name: "Sesame oil" },
      { name: "Cornstarch" },
      { name: "Stir-fry vegetables" },
    ],
    steps: [
      "Press and cube tofu",
      "Marinate tofu in soy sauce, rice vinegar, and sesame oil (optional)",
      "Heat oil in a pan and stir-fry tofu until golden brown",
      "Add vegetables and stir-fry until tender-crisp",
      "Make a cornstarch slurry (optional) with cornstarch and water to thicken the sauce (optional)",
      "Serve over rice or noodles",
    ],
    servings: 2,
    servingSizes: [{ scale: 1, qty: 1, units: "bowl" }],
    ratings: 4.1,
    users: 57,
    img: "https://www.wellplated.com/wp-content/uploads/2019/03/How-to-Make-Tofu-Stir-Fry.jpg",
  },
  {
    id: "6",
    name: "Lemon Chicken Piccata",
    username: "John Doe",
    tags: ["italian", "chicken", "main course", "lemon", "dinner", "lunch"],
    prepareTime: 15,
    cookTime: 20,
    ingredients: [
      { name: "Chicken breasts" },
      { name: "Flour" },
      { name: "Eggs" },
      { name: "Butter" },
      { name: "Lemon juice" },
      { name: "Capers" },
      { name: "Parsley" },
    ],
    steps: [
      "Dredge chicken in flour, then egg",
      "Saute chicken in butter",
      "Add lemon juice, capers, and parsley to pan sauce",
      "Serve chicken with pan sauce",
    ],
    servings: 4,
    servingSizes: [{ scale: 1, qty: 1, units: "serving" }],
    ratings: 4.1,
    users: 23,
    img: "http://www.homemadeitaliancooking.com/wp-content/uploads/2016/02/Chicekn-Picatta-2.jpg ",
  },
  {
    id: "7",
    name: "Thai Peanut Curry",
    username: "John Doe",
    tags: ["thai", "curry", "vegetarian", "peanut", "dinner", "lunch"],
    prepareTime: 20,
    cookTime: 30,
    ingredients: [
      { name: "Vegetable broth" },
      { name: "Coconut milk" },
      { name: "Peanut butter" },
      { name: "Curry paste" },
      { name: "Bell peppers" },
      { name: "Broccoli" },
      { name: "Lime juice" },
      { name: "Cilantro" },
    ],
    steps: [
      "Simmer vegetable broth, coconut milk, peanut butter, and curry paste",
      "Add vegetables and simmer until tender",
      "Stir in lime juice and cilantro",
      "Serve over rice",
    ],
    servings: 4,
    servingSizes: [{ scale: 1, qty: 1, units: "serving" }],
    ratings: 3.8,
    users: 102,
    img: "https://shelikesgreens.com/wp-content/uploads/2020/11/00100dPORTRAIT_00100_BURST20200530153709349_COVER-01-1-1024x768.jpg ",
  },
  {
    id: "8",
    name: "Cheesy Enchiladas",
    username: "John Doe",
    tags: ["mexican", "enchiladas", "cheese", "dinner", "lunch"],
    prepareTime: 20,
    cookTime: 30,
    ingredients: [
      { name: "Tortillas" },
      { name: "Shredded chicken" },
      { name: "Cheese" },
      { name: "Enchilada sauce" },
      { name: "Beans" },
      { name: "Onion" },
      { name: "Cilantro" },
    ],
    steps: [
      "Fill tortillas with chicken, cheese, and beans",
      "Roll up tortillas and place in a baking dish",
      "Top with enchilada sauce and cheese",
      "Bake until bubbly",
    ],
    servings: 6,
    servingSizes: [{ scale: 1, qty: 1, units: "serving" }],
    ratings: 3.5,
    users: 43,
    img: "https://www.southernkissed.com/wp-content/uploads/2018/09/zesty-cheesy-enchiladas.jpg ",
  },
  {
    id: "21",
    name: "Tandoori Chicken",
    username: "John Doe",
    tags: ["indian", "chicken", "main course", "dinner", "lunch"],
    prepareTime: 30,
    cookTime: 40,
    ingredients: [
      { name: "Chicken thighs" },
      { name: "Yogurt" },
      { name: "Lemon juice" },
      { name: "Ginger garlic paste" },
      { name: "Tandoori masala" },
      { name: "Vegetable oil" },
      { name: "Cilantro", optional: true },
    ],
    steps: [
      "Marinate chicken in yogurt, lemon juice, ginger garlic paste, and tandoori masala for at least 30 minutes",
      "Preheat oven to 400°F (200°C)",
      "Brush chicken with oil and bake for 30-40 minutes, or until cooked through",
      "Garnish with cilantro (optional)",
    ],
    servings: 4,
    servingSizes: [{ scale: 1, qty: 1, units: "serving" }],
    ratings: 4.4,
    users: 227,
    img: "https://i0.wp.com/d1eha6vqc5cqta.cloudfront.net/2014/06/tandoori-chicken-2.jpg?fit=1366%2C911&ssl=1 ",
  },
  {
    id: "22",
    name: "Pad Thai",
    username: "John Smith",
    tags: ["thai", "stir-fry", "noodles", "vegetarian", "lunch", "dinner"],
    prepareTime: 15,
    cookTime: 20,
    ingredients: [
      { name: "Rice noodles" },
      { name: "Eggs" },
      { name: "Bean sprouts" },
      { name: "Green onions" },
      { name: "Tofu", optional: true },
      { name: "Peanuts" },
      { name: "Pad Thai sauce" },
    ],
    steps: [
      "Soak rice noodles according to package instructions",
      "Scramble eggs in a pan",
      "Add vegetables and tofu (if using) and stir-fry until tender",
      "Add cooked noodles, pad thai sauce, and peanuts, and stir-fry until heated through",
    ],
    servings: 2,
    servingSizes: [{ scale: 1, qty: 1, units: "serving" }],
    ratings: 4.7,
    users: 89,
    img: "http://wickedfood.co.za/wp-content/uploads/2009/05/pad-thai.jpg ",
  },
  {
    id: "23",
    name: "Chicken Pot Pie",
    username: "Emily",
    tags: ["american", "comfort food", "chicken", "dinner"],
    prepareTime: 45,
    cookTime: 60,
    ingredients: [
      { name: "Pie crust" },
      { name: "Chicken breasts" },
      { name: "Carrots" },
      { name: "Peas" },
      { name: "Celery" },
      { name: "Chicken broth" },
      { name: "Flour" },
      { name: "Heavy cream" },
      { name: "Dried herbs" },
    ],
    steps: [
      "Cook chicken and vegetables in chicken broth",
      "Prepare a roux with flour and butter, then whisk in broth and cream to make a gravy",
      "Stir cooked chicken and vegetables into the gravy",
      "Line a pie dish with pie crust, fill with chicken mixture, and top with another crust",
      "Bake until golden brown and bubbly",
    ],
    servings: 6,
    servingSizes: [{ scale: 1, qty: 1, units: "serving" }],
    ratings: 4.0,
    users: 99,
    img: "https://iheartrecipes.com/wp-content/uploads/2017/10/DSC_9841.jpg ",
  },
  {
    id: "1",
    name: "Chicken Alfredo",
    username: "Michael Brown",
    tags: ["italian", "pasta", "chicken", "dinner"],
    prepareTime: 30,
    cookTime: 20,
    ingredients: [
      { name: "Boneless, skinless chicken breasts" },
      { name: "Dried fettuccine or other pasta" },
      { name: "Heavy cream" },
      { name: "Parmesan cheese" },
      { name: "Butter" },
      { name: "Garlic" },
      { name: "Italian seasoning" },
      { name: "Salt and pepper" },
    ],
    steps: [
      "Cook chicken breasts and shred",
      "Cook pasta according to package instructions",
      "Melt butter in a pan, saute garlic",
      "Stir in heavy cream, parmesan cheese, and seasonings",
      "Simmer sauce until thickened",
      "Combine cooked chicken, pasta, and sauce",
      "Serve with additional parmesan cheese (optional)",
    ],
    servings: 4,
    servingSizes: [{ scale: 1, qty: 1, units: "plate" }],
    ratings: 3.9,
    users: 111,
    img: "https://www.multivu.com/players/English/7303853-olive-garden-never-ending-pasta-bowl/image/chicken-alfredo-null-HR.jpg ",
  },
  {
    id: "2",
    name: "Lasagna",
    username: "John Doe",
    tags: ["italian", "pasta", "meat", "vegetarian (optional)", "baking"],
    prepareTime: 45,
    cookTime: 40,
    ingredients: [
      { name: "Ground beef (or ricotta cheese for vegetarian option)" },
      { name: "Lasagna noodles" },
      { name: "Marinara sauce" },
      { name: "Ricotta cheese" },
      { name: "Mozzarella cheese" },
      { name: "Parmesan cheese" },
      { name: "Onion" },
      { name: "Garlic" },
      { name: "Italian seasoning" },
    ],
    steps: [
      "Brown ground beef (or prepare ricotta cheese mixture)",
      "Saute onion and garlic in a pan",
      "Assemble lasagna layers: sauce, noodles, ricotta cheese, mozzarella cheese",
      "Repeat layers, ending with cheese on top",
      "Bake at 375°F for 40 minutes, or until bubbly and golden brown",
    ],
    servings: 6,
    servingSizes: [{ scale: 1, qty: 1 }],
    ratings: 4.8,
    users: 589,
    img: "https://fthmb.tqn.com/albxRDFRdI7_Xcm2mIj24o0uHyY=/960x0/filters:no_upscale()/meaty-lasagna-95697781-57bbb55b3df78c876364529c.jpg ",
  },
  {
    id: "3",
    name: "Mac and Cheese",
    username: "John Smith",
    tags: ["pasta", "cheese", "comfort food", "side dish"],
    prepareTime: 20,
    cookTime: 20,
    ingredients: [
      { name: "Elbow macaroni pasta" },
      { name: "Cheddar cheese" },
      { name: "Milk" },
      { name: "Butter" },
      { name: "Flour" },
      { name: "Salt and pepper" },
    ],
    steps: [
      "Cook elbow macaroni according to package instructions",
      "Melt butter in a pan, whisk in flour",
      "Slowly whisk in milk to create a roux",
      "Stir in grated cheddar cheese until melted",
      "Combine cooked macaroni with cheese sauce",
      "Season with salt and pepper, bake for 10 minutes (optional) for a crispy top",
    ],
    servings: 4,
    servingSizes: [{ scale: 1, qty: 1 }],
    ratings: 3.2,
    users: 12,
    img: "https://norecipes.com/wp-content/uploads/2017/12/best-macaroni-and-cheese_006.jpg ",
  },
  {
    id: "5",
    name: "Penne Arrabbiata",
    username: "William Davis",
    tags: ["italian", "pasta", "spicy", "vegetarian"],
    prepareTime: 20,
    cookTime: 15,
    ingredients: [
      { name: "Penne pasta" },
      { name: "Crushed tomatoes" },
      { name: "Garlic" },
      { name: "Red pepper flakes" },
      { name: "Olive oil" },
      { name: "Fresh basil (optional)" },
      { name: "Salt and pepper" },
    ],
    steps: [
      "Cook penne pasta according to package instructions",
      "Heat olive oil in a pan, saute garlic",
      "Add crushed tomatoes and red pepper flakes, simmer",
      "Season with salt and pepper",
      "Toss cooked pasta with the sauce",
      "Garnish with fresh basil (optional)",
    ],
    servings: 4,
    servingSizes: [{ scale: 1, qty: 1 }],
    ratings: 2.3,
    users: 3,
    img: "https://www.healthbenefitstimes.com/recipe/wp-content/uploads/2019/02/Penne-arrabbiata-recipe.jpg ",
  },
  {
    id: "15",
    name: "Shrimp Scampi",
    username: "Emily",
    tags: ["seafood", "pasta", "garlic", "lemon"],
    prepareTime: 20,
    cookTime: 15,
    ingredients: [
      { name: "Shrimp, peeled and deveined" },
      { name: "Pasta (your choice)" },
      { name: "Butter" },
      { name: "Garlic" },
      { name: "Lemon juice" },
      { name: "White wine (optional)" },
      { name: "Fresh parsley" },
      { name: "Salt and pepper" },
    ],
    steps: [
      "Cook pasta according to package instructions",
      "Melt butter in a pan, saute garlic",
      "Add shrimp and cook until pink and opaque",
      "Deglaze the pan with white wine (optional)",
      "Stir in lemon juice, parsley, and seasonings",
      "Toss cooked pasta with the shrimp scampi sauce",
    ],
    servings: 4,
    servingSizes: [{ scale: 1, qty: 1 }],
    ratings: 3.6,
    users: 65,
    img: "https://www.thespruceeats.com/thmb/GD6RGy7TIl4FL003iTp6-rwiZEk=/6192x4128/filters:fill(auto,1)/shrimp-scampi-with-garlic-3060877-hero-01-03f3e71db28a4efb930264fce4d9a6f6.jpg ",
  },
];

export default data;
